//
// SECURITY: see functions/_shared/admin-auth.ts header.
//
// Streams the R2 file body to the browser, gated by an HMAC signature
// generated by the sibling `/url` endpoint. SYSTEM_CRON_SECRET MUST be
// set in production; the endpoint hard-fails (500) if it isn't.

import type { PagesFunction, Env } from '../../../../../../_shared/types';
import { json } from '../../../../../../_shared/json';
import { first } from '../../../../../../_shared/db';
import { hmacVerify } from '../../../../../../_shared/hmac';
import { requireSecret, MissingSecretError } from '../../../../../../_shared/secrets';

interface ParamsLocal {
  id: string;
  docTypeId: string;
}

export const onRequestGet: PagesFunction<
  Env & { SYSTEM_CRON_SECRET?: string },
  keyof ParamsLocal
> = async ({ request, env, params }) => {
  const url = new URL(request.url);
  const expires = parseInt(url.searchParams.get('expires') ?? '0', 10);
  const sig = url.searchParams.get('sig') ?? '';
  if (!expires || !sig) return json({ error: 'missing token' }, { status: 401 });
  if (Date.now() / 1000 > expires) return json({ error: 'token expired' }, { status: 401 });

  let secret: string;
  try {
    secret = requireSecret(env as unknown as Record<string, unknown>, 'SYSTEM_CRON_SECRET');
  } catch (err) {
    if (err instanceof MissingSecretError) {
      console.error(err.message);
      return json({ error: 'server misconfigured' }, { status: 500 });
    }
    throw err;
  }

  const p = params as unknown as ParamsLocal;
  const ok = await hmacVerify(secret, `${p.id}:${p.docTypeId}:${expires}`, sig);
  if (!ok) return json({ error: 'invalid token' }, { status: 401 });

  const row = await first<{ r2_key: string; mime_type: string; original_filename: string }>(
    env,
    'SELECT r2_key, mime_type, original_filename FROM application_documents WHERE application_id = ? AND document_type_id = ?',
    p.id,
    p.docTypeId,
  );
  if (!row) return json({ error: 'document not found' }, { status: 404 });

  const obj = await env.UPLOADS.get(row.r2_key);
  if (!obj) return json({ error: 'file missing in R2' }, { status: 404 });

  return new Response(obj.body, {
    headers: {
      'content-type': row.mime_type,
      'content-disposition': `inline; filename="${row.original_filename}"`,
      'cache-control': 'private, max-age=60',
    },
  });
};
