// Streams the R2 file body to the browser, gated by an HMAC signature
// generated by the sibling `/url` endpoint. Validates the token (timing
// attacks are not a concern here — the secret is unguessable and the
// token is single-use within its 60s window).

import type { PagesFunction, Env } from '../../../../../../_shared/types';
import { json } from '../../../../../../_shared/json';
import { first } from '../../../../../../_shared/db';

async function hmacToken(secret: string, payload: string): Promise<string> {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw',
    enc.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
  const sig = await crypto.subtle.sign('HMAC', key, enc.encode(payload));
  return btoa(String.fromCharCode(...new Uint8Array(sig)))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

interface ParamsLocal {
  id: string;
  docTypeId: string;
}

export const onRequestGet: PagesFunction<
  Env & { SYSTEM_CRON_SECRET?: string },
  keyof ParamsLocal
> = async ({ request, env, params }) => {
  const url = new URL(request.url);
  const expires = parseInt(url.searchParams.get('expires') ?? '0', 10);
  const sig = url.searchParams.get('sig') ?? '';
  if (!expires || !sig) return json({ error: 'missing token' }, { status: 401 });
  if (Date.now() / 1000 > expires) return json({ error: 'token expired' }, { status: 401 });

  const p = params as unknown as ParamsLocal;
  const secret = env.SYSTEM_CRON_SECRET ?? 'dev-secret-not-for-prod';
  const expectedSig = await hmacToken(secret, `${p.id}:${p.docTypeId}:${expires}`);
  if (sig !== expectedSig) return json({ error: 'invalid token' }, { status: 401 });

  const row = await first<{ r2_key: string; mime_type: string; original_filename: string }>(
    env,
    'SELECT r2_key, mime_type, original_filename FROM application_documents WHERE application_id = ? AND document_type_id = ?',
    p.id,
    p.docTypeId,
  );
  if (!row) return json({ error: 'document not found' }, { status: 404 });

  const obj = await env.UPLOADS.get(row.r2_key);
  if (!obj) return json({ error: 'file missing in R2' }, { status: 404 });

  return new Response(obj.body, {
    headers: {
      'content-type': row.mime_type,
      'content-disposition': `inline; filename="${row.original_filename}"`,
      'cache-control': 'private, max-age=60',
    },
  });
};
